// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sample.proto

#include "sample.pb.h"
#include "sample.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpcTest {

static const char* GrpcTestService_method_names[] = {
  "/grpcTest.GrpcTestService/getData",
};

std::unique_ptr< GrpcTestService::Stub> GrpcTestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GrpcTestService::Stub> stub(new GrpcTestService::Stub(channel, options));
  return stub;
}

GrpcTestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getData_(GrpcTestService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GrpcTestService::Stub::getData(::grpc::ClientContext* context, const ::grpcTest::request& request, ::grpcTest::respond* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpcTest::request, ::grpcTest::respond, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getData_, context, request, response);
}

void GrpcTestService::Stub::async::getData(::grpc::ClientContext* context, const ::grpcTest::request* request, ::grpcTest::respond* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpcTest::request, ::grpcTest::respond, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getData_, context, request, response, std::move(f));
}

void GrpcTestService::Stub::async::getData(::grpc::ClientContext* context, const ::grpcTest::request* request, ::grpcTest::respond* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpcTest::respond>* GrpcTestService::Stub::PrepareAsyncgetDataRaw(::grpc::ClientContext* context, const ::grpcTest::request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpcTest::respond, ::grpcTest::request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpcTest::respond>* GrpcTestService::Stub::AsyncgetDataRaw(::grpc::ClientContext* context, const ::grpcTest::request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

GrpcTestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcTestService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcTestService::Service, ::grpcTest::request, ::grpcTest::respond, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcTestService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpcTest::request* req,
             ::grpcTest::respond* resp) {
               return service->getData(ctx, req, resp);
             }, this)));
}

GrpcTestService::Service::~Service() {
}

::grpc::Status GrpcTestService::Service::getData(::grpc::ServerContext* context, const ::grpcTest::request* request, ::grpcTest::respond* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpcTest

