// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sample.proto
#ifndef GRPC_sample_2eproto__INCLUDED
#define GRPC_sample_2eproto__INCLUDED

#include "sample.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpcTest {

// The greeting service definition.
class GrpcTestService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpcTest.GrpcTestService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status receiveData(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpcTest::pkg1* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcTest::pkg1>> AsyncreceiveData(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcTest::pkg1>>(AsyncreceiveDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcTest::pkg1>> PrepareAsyncreceiveData(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcTest::pkg1>>(PrepareAsyncreceiveDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      virtual void receiveData(::grpc::ClientContext* context, const ::grpcTest::pkg* request, ::grpcTest::pkg1* response, std::function<void(::grpc::Status)>) = 0;
      virtual void receiveData(::grpc::ClientContext* context, const ::grpcTest::pkg* request, ::grpcTest::pkg1* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcTest::pkg1>* AsyncreceiveDataRaw(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcTest::pkg1>* PrepareAsyncreceiveDataRaw(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status receiveData(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpcTest::pkg1* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcTest::pkg1>> AsyncreceiveData(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcTest::pkg1>>(AsyncreceiveDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcTest::pkg1>> PrepareAsyncreceiveData(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcTest::pkg1>>(PrepareAsyncreceiveDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void receiveData(::grpc::ClientContext* context, const ::grpcTest::pkg* request, ::grpcTest::pkg1* response, std::function<void(::grpc::Status)>) override;
      void receiveData(::grpc::ClientContext* context, const ::grpcTest::pkg* request, ::grpcTest::pkg1* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpcTest::pkg1>* AsyncreceiveDataRaw(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpcTest::pkg1>* PrepareAsyncreceiveDataRaw(::grpc::ClientContext* context, const ::grpcTest::pkg& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_receiveData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status receiveData(::grpc::ServerContext* context, const ::grpcTest::pkg* request, ::grpcTest::pkg1* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_receiveData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_receiveData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_receiveData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receiveData(::grpc::ServerContext* /*context*/, const ::grpcTest::pkg* /*request*/, ::grpcTest::pkg1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestreceiveData(::grpc::ServerContext* context, ::grpcTest::pkg* request, ::grpc::ServerAsyncResponseWriter< ::grpcTest::pkg1>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_receiveData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_receiveData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_receiveData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpcTest::pkg, ::grpcTest::pkg1>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpcTest::pkg* request, ::grpcTest::pkg1* response) { return this->receiveData(context, request, response); }));}
    void SetMessageAllocatorFor_receiveData(
        ::grpc::MessageAllocator< ::grpcTest::pkg, ::grpcTest::pkg1>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpcTest::pkg, ::grpcTest::pkg1>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_receiveData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receiveData(::grpc::ServerContext* /*context*/, const ::grpcTest::pkg* /*request*/, ::grpcTest::pkg1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* receiveData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpcTest::pkg* /*request*/, ::grpcTest::pkg1* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_receiveData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_receiveData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_receiveData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_receiveData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receiveData(::grpc::ServerContext* /*context*/, const ::grpcTest::pkg* /*request*/, ::grpcTest::pkg1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_receiveData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_receiveData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_receiveData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receiveData(::grpc::ServerContext* /*context*/, const ::grpcTest::pkg* /*request*/, ::grpcTest::pkg1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestreceiveData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_receiveData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_receiveData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->receiveData(context, request, response); }));
    }
    ~WithRawCallbackMethod_receiveData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receiveData(::grpc::ServerContext* /*context*/, const ::grpcTest::pkg* /*request*/, ::grpcTest::pkg1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* receiveData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_receiveData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_receiveData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpcTest::pkg, ::grpcTest::pkg1>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpcTest::pkg, ::grpcTest::pkg1>* streamer) {
                       return this->StreamedreceiveData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_receiveData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status receiveData(::grpc::ServerContext* /*context*/, const ::grpcTest::pkg* /*request*/, ::grpcTest::pkg1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedreceiveData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpcTest::pkg,::grpcTest::pkg1>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_receiveData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_receiveData<Service > StreamedService;
};

}  // namespace grpcTest


#endif  // GRPC_sample_2eproto__INCLUDED
